# Generated by Django 4.2.6 on 2023-10-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusinessHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_id", models.PositiveBigIntegerField(db_index=True)),
                ("day", models.IntegerField()),
                ("start_time_local", models.TimeField()),
                ("end_time_local", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="StoreStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_id", models.PositiveBigIntegerField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        max_length=10,
                    ),
                ),
                ("timestamp_utc", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Timezones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_id", models.PositiveBigIntegerField(db_index=True)),
                ("timezone_str", models.CharField(max_length=100)),
            ],
        ),
    ]
